context:
    resource: "@ContextBundle/Controller/"
    type:     annotation
    prefix:   /

string_value:
    resource: "@StringValueBundle/Controller/"
    type:     annotation
    prefix:   /

operating_system:
    resource: "@OperatingSystemBundle/Controller/"
    type:     annotation
    prefix:   /

string_key:
    resource: "@StringKeyBundle/Controller/"
    type:     annotation
    prefix:   /

lang:
    resource: "@LangBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

project:
    resource: "@ProjectBundle/Controller/"
    type:     annotation
    prefix:   /

home_page:
    resource: "@HomePageBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults:
        _controller: HomePageBundle:Default:index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"