<?php

namespace Frontend\ContextBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContextRepository extends EntityRepository
{
}
